spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/Devansh-ds/Ecommerce-Config

server:
  port: 8087
